class NotificationsData {
  static List<Map<String, dynamic>> notifications = [
    {
      'type': 'posted',
      'name': 'John Doe',
      'post': 'Excited about my new project!',
      'image': 'https://via.placeholder.com/150/FF5733/000000?text=P',
    },
    {
      'type': 'congratsnewposition',
      'name': 'Jane Smith',
      'position': 'Senior Developer',
      'company': 'XYZ Tech',
      'image': 'https://via.placeholder.com/150/33FF57/000000?text=C',
    },
    {
      'type': 'congratsAniversary',
      'name': 'Alex Johnson',
      'years': '3',
      'company': 'ABC Corporation',
      'image': 'https://via.placeholder.com/150/5733FF/000000?text=A',
    },
    {
      'type': 'viewedProfile',
      'name': 'Emily Davis',
      'image': 'https://via.placeholder.com/150/FF5733/000000?text=V',
    },
    {
      'type': 'opertunities',
      'position': 'Product Manager',
      'number': '5',
      'place': 'New York',
      'image': 'https://via.placeholder.com/150/33FF57/000000?text=O',
    },
    {
      'type': 'posted',
      'name': 'Alice Brown',
      'post': 'Just launched my new website!',
      'image': 'https://via.placeholder.com/150/FF5733/000000?text=P',
    },
    {
      'type': 'congratsnewposition',
      'name': 'Robert White',
      'position': 'Data Scientist',
      'company': 'Data Insights',
      'image': 'https://via.placeholder.com/150/33FF57/000000?text=D',
    },
    {
      'type': 'congratsAniversary',
      'name': 'Grace Turner',
      'years': '1',
      'company': 'Tech Innovators',
      'image': 'https://via.placeholder.com/150/5733FF/000000?text=T',
    },
    {
      'type': 'viewedProfile',
      'name': 'Michael Reed',
      'image': 'https://via.placeholder.com/150/FF5733/000000?text=V',
    },
    {
      'type': 'opertunities',
      'position': 'Marketing Coordinator',
      'number': '3',
      'place': 'San Francisco',
      'image': 'https://via.placeholder.com/150/33FF57/000000?text=M',
    },
    {
      'type': 'posted',
      'name': 'Samuel Clark',
      'post': 'Reached a milestone in my project!',
      'image': 'https://via.placeholder.com/150/FF5733/000000?text=R',
    },
    {
      'type': 'congratsnewposition',
      'name': 'Olivia Taylor',
      'position': 'UX/UI Designer',
      'company': 'Design Studios',
      'image': 'https://via.placeholder.com/150/33FF57/000000?text=U',
    },
    {
      'type': 'congratsAniversary',
      'name': 'Daniel Miller',
      'years': '2',
      'company': 'Innovate Solutions',
      'image': 'https://via.placeholder.com/150/5733FF/000000?text=I',
    },
    {
      'type': 'viewedProfile',
      'name': 'Sophia Turner',
      'image': 'https://via.placeholder.com/150/FF5733/000000?text=S',
    },
    {
      'type': 'opertunities',
      'position': 'Software Engineer',
      'number': '8',
      'place': 'Seattle',
      'image': 'https://via.placeholder.com/150/33FF57/000000?text=S',
    },
    {
      'type': 'posted',
      'name': 'Ethan Harris',
      'post': 'Happy to share my latest achievement!',
      'image': 'https://via.placeholder.com/150/FF5733/000000?text=H',
    },
    {
      'type': 'congratsnewposition',
      'name': 'Isabella Wilson',
      'position': 'Product Manager',
      'company': 'Tech Innovations',
      'image': 'https://via.placeholder.com/150/33FF57/000000?text=I',
    },
    {
      'type': 'congratsAniversary',
      'name': 'Mason Turner',
      'years': '4',
      'company': 'Innovate Tech',
      'image': 'https://via.placeholder.com/150/5733FF/000000?text=M',
    },
    {
      'type': 'viewedProfile',
      'name': 'Ava Davis',
      'image': 'https://via.placeholder.com/150/FF5733/000000?text=A',
    },
    {
      'type': 'opertunities',
      'position': 'Sales Representative',
      'number': '6',
      'place': 'Chicago',
      'image': 'https://via.placeholder.com/150/33FF57/000000?text=S',
    },
  ];
}
