class NOtificationsData {
  static List<Map<String, dynamic>> notifications = [
    {
      'type': 'posted',
      'name': 'John Doe',
      'post': 'Excited about my new project!',
      'image': 'https://placeholder.com/1',
    },
    {
      'type': 'congratsnewposition',
      'name': 'Jane Smith',
      'position': 'Senior Developer',
      'company': 'XYZ Tech',
      'image': 'https://placeholder.com/2',
    },
    {
      'type': 'congratsAniversary',
      'name': 'Alex Johnson',
      'years': 3,
      'company': 'ABC Corporation',
      'image': 'https://placeholder.com/3',
    },
    {
      'type': 'viewedProfile',
      'name': 'Emily Davis',
      'image': 'https://placeholder.com/4',
    },
    {
      'type': 'opertunities',
      'position': 'Product Manager',
      'number': '5',
      'place': 'New York',
      'image': 'https://placeholder.com/5',
    },
    {
      'type': 'posted',
      'name': 'Alice Brown',
      'post': 'Just launched my new website!',
      'image': 'https://placeholder.com/6',
    },
    {
      'type': 'congratsnewposition',
      'name': 'Robert White',
      'position': 'Data Scientist',
      'company': 'Data Insights',
      'image': 'https://placeholder.com/7',
    },
    {
      'type': 'congratsAniversary',
      'name': 'Grace Turner',
      'years': '1',
      'company': 'Tech Innovators',
      'image': 'https://placeholder.com/8',
    },
    {
      'type': 'viewedProfile',
      'name': 'Michael Reed',
      'image': 'https://placeholder.com/9',
    },
    {
      'type': 'opertunities',
      'position': 'Marketing Coordinator',
      'number': '3',
      'place': 'San Francisco',
      'image': 'https://placeholder.com/10',
    },
    {
      'type': 'posted',
      'name': 'Samuel Clark',
      'post': 'Reached a milestone in my project!',
      'image': 'https://placeholder.com/11',
    },
    {
      'type': 'congratsnewposition',
      'name': 'Olivia Taylor',
      'position': 'UX/UI Designer',
      'company': 'Design Studios',
      'image': 'https://placeholder.com/12',
    },
    {
      'type': 'congratsAniversary',
      'name': 'Daniel Miller',
      'years': '2',
      'company': 'Innovate Solutions',
      'image': 'https://placeholder.com/13',
    },
    {
      'type': 'viewedProfile',
      'name': 'Sophia Turner',
      'image': 'https://placeholder.com/14',
    },
    {
      'type': 'opertunities',
      'position': 'Software Engineer',
      'number': '8',
      'place': 'Seattle',
      'image': 'https://placeholder.com/15',
    },
    {
      'type': 'posted',
      'name': 'Ethan Harris',
      'post': 'Happy to share my latest achievement!',
      'image': 'https://placeholder.com/16',
    },
    {
      'type': 'congratsnewposition',
      'name': 'Isabella Wilson',
      'position': 'Product Manager',
      'company': 'Tech Innovations',
      'image': 'https://placeholder.com/17',
    },
    {
      'type': 'congratsAniversary',
      'name': 'Mason Turner',
      'years': '4',
      'company': 'Innovate Tech',
      'image': 'https://placeholder.com/18',
    },
    {
      'type': 'viewedProfile',
      'name': 'Ava Davis',
      'image': 'https://placeholder.com/19',
    },
    {
      'type': 'opertunities',
      'position': 'Sales Representative',
      'number': '6',
      'place': 'Chicago',
      'image': 'https://placeholder.com/20',
    },
  ];
}
