class JobDatabase {
  static List<Map<String, dynamic>> jobPostings = [
    {
      'jobTitle': 'Software Engineer',
      'address': '123 Main Street',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Tech Innovations',
      'location': 'San Francisco, California, USA',
      'remoteStatus': 'Hybrid',
      'timePosted': '2 hours ago',
    },
    {
      'jobTitle': 'Data Scientist',
      'address': '456 Oak Avenue',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Data Insights',
      'location': 'New York, New York, USA',
      'remoteStatus': 'Remote',
      'timePosted': '1 day ago',
    },
    {
      'jobTitle': 'UX/UI Designer',
      'address': '789 Pine Lane',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Design Studios',
      'location': 'Los Angeles, California, USA',
      'remoteStatus': 'Online',
      'timePosted': '3 days ago',
    },
    {
      'jobTitle': 'Flutter Developer',
      'address': '101 River Road',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Mobile Apps Inc.',
      'location': 'Austin, Texas, USA',
      'remoteStatus': 'Remote',
      'timePosted': '4 days ago',
    },
    {
      'jobTitle': 'Android Developer',
      'address': '202 Forest Avenue',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Android Solutions',
      'location': 'Seattle, Washington, USA',
      'remoteStatus': 'Hybrid',
      'timePosted': '5 days ago',
    },
    {
      'jobTitle': 'iOS Developer',
      'address': '303 Mountain Street',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'iOS Innovators',
      'location': 'Chicago, Illinois, USA',
      'remoteStatus': 'Remote',
      'timePosted': '6 days ago',
    },
    {
      'jobTitle': 'Front-end Developer',
      'address': '404 Lakeview Drive',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Web World Inc.',
      'location': 'Miami, Florida, USA',
      'remoteStatus': 'Online',
      'timePosted': '1 week ago',
    },
    {
      'jobTitle': 'Back-end Developer',
      'address': '505 Oakwood Lane',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Server Solutions',
      'location': 'Denver, Colorado, USA',
      'remoteStatus': 'Remote',
      'timePosted': '1 week ago',
    },
    {
      'jobTitle': 'Full Stack Developer',
      'address': '606 Riverfront Road',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Code Creators',
      'location': 'Portland, Oregon, USA',
      'remoteStatus': 'Hybrid',
      'timePosted': '2 weeks ago',
    },
    {
      'jobTitle': 'UI Designer',
      'address': '707 Pinecrest Avenue',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'UI Wizards',
      'location': 'San Diego, California, USA',
      'remoteStatus': 'Online',
      'timePosted': '2 weeks ago',
    },
    {
      'jobTitle': 'Quality Assurance Engineer',
      'address': '808 Cypress Street',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'QA Experts',
      'location': 'Houston, Texas, USA',
      'remoteStatus': 'Remote',
      'timePosted': '3 weeks ago',
    },
    {
      'jobTitle': 'Product Manager',
      'address': '909 Elmwood Drive',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Product Visionaries',
      'location': 'Phoenix, Arizona, USA',
      'remoteStatus': 'Hybrid',
      'timePosted': '3 weeks ago',
    },
    {
      'jobTitle': 'DevOps Engineer',
      'address': '1010 Oakridge Avenue',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'DevOps Solutions',
      'location': 'Minneapolis, Minnesota, USA',
      'remoteStatus': 'Remote',
      'timePosted': '4 weeks ago',
    },
    {
      'jobTitle': 'Network Engineer',
      'address': '1111 Maple Drive',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Network Innovators',
      'location': 'Philadelphia, Pennsylvania, USA',
      'remoteStatus': 'Online',
      'timePosted': '4 weeks ago',
    },
    {
      'jobTitle': 'Machine Learning Engineer',
      'address': '1212 Cedar Road',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'AI Creations',
      'location': 'Atlanta, Georgia, USA',
      'remoteStatus': 'Remote',
      'timePosted': '5 weeks ago',
    },
    {
      'jobTitle': 'Data Analyst',
      'address': '1313 Birch Lane',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Data Crunchers',
      'location': 'Boston, Massachusetts, USA',
      'remoteStatus': 'Online',
      'timePosted': '5 weeks ago',
    },
    {
      'jobTitle': 'Cybersecurity Analyst',
      'address': '1414 Cedar Avenue',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Secure Solutions',
      'location': 'Washington, D.C., USA',
      'remoteStatus': 'Remote',
      'timePosted': '6 weeks ago',
    },
    {
      'jobTitle': 'Cloud Solutions Architect',
      'address': '1515 Elm Street',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Cloud Innovations',
      'location': 'Dallas, Texas, USA',
      'remoteStatus': 'Hybrid',
      'timePosted': '7 weeks ago',
    },
    {
      'jobTitle': 'Game Developer',
      'address': '1616 Oakwood Road',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Game Studios',
      'location': 'Orlando, Florida, USA',
      'remoteStatus': 'Remote',
      'timePosted': '8 weeks ago',
    },
    {
      'jobTitle': 'Embedded Systems Engineer',
      'address': '1717 Pinecrest Lane',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Embedded Tech Solutions',
      'location': 'San Jose, California, USA',
      'remoteStatus': 'Online',
      'timePosted': '8 weeks ago',
    },
    {
      'jobTitle': 'IT Support Specialist',
      'address': '1818 Birch Avenue',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'IT Support Experts',
      'location': 'Raleigh, North Carolina, USA',
      'remoteStatus': 'Remote',
      'timePosted': '9 weeks ago',
    },
    {
      'jobTitle': 'Technical Writer',
      'address': '1919 Cedar Lane',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Docs and Code',
      'location': 'Pittsburgh, Pennsylvania, USA',
      'remoteStatus': 'Hybrid',
      'timePosted': '10 weeks ago',
    },
    {
      'jobTitle': 'Robotics Engineer',
      'address': '2020 Oakridge Drive',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'RoboTech Innovations',
      'location': 'Detroit, Michigan, USA',
      'remoteStatus': 'Remote',
      'timePosted': '11 weeks ago',
    },
    {
      'jobTitle': 'UI/UX Researcher',
      'address': '2121 Elmwood Road',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Research Labs',
      'location': 'Cambridge, Massachusetts, USA',
      'remoteStatus': 'Online',
      'timePosted': '12 weeks ago',
    },
    {
      'jobTitle': 'Systems Administrator',
      'address': '2222 Cypress Avenue',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'System Experts',
      'location': 'Salt Lake City, Utah, USA',
      'remoteStatus': 'Remote',
      'timePosted': '12 weeks ago',
    },
    {
      'jobTitle': 'Business Analyst',
      'address': '2323 Pinecrest Street',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Business Solutions',
      'location': 'Kansas City, Missouri, USA',
      'remoteStatus': 'Hybrid',
      'timePosted': '13 weeks ago',
    },
    {
      'jobTitle': 'Network Security Engineer',
      'address': '2424 Oakwood Lane',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Security Innovations',
      'location': 'Charlotte, North Carolina, USA',
      'remoteStatus': 'Online',
      'timePosted': '14 weeks ago',
    },
    {
      'jobTitle': 'Product Designer',
      'address': '2525 Birch Road',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Product Design Studios',
      'location': 'Denver, Colorado, USA',
      'remoteStatus': 'Remote',
      'timePosted': '15 weeks ago',
    },
    {
      'jobTitle': 'Digital Marketing Specialist',
      'address': '2626 Cedar Street',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Digital Marketing Experts',
      'location': 'Austin, Texas, USA',
      'remoteStatus': 'Hybrid',
      'timePosted': '16 weeks ago',
    },
    {
      'jobTitle': 'Machine Vision Engineer',
      'address': '2727 Elmwood Drive',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Vision Tech Solutions',
      'location': 'San Diego, California, USA',
      'remoteStatus': 'Remote',
      'timePosted': '17 weeks ago',
    },
    {
      'jobTitle': 'Sales Representative',
      'address': '2828 Cypress Road',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Sales Experts Inc.',
      'location': 'Nashville, Tennessee, USA',
      'remoteStatus': 'Online',
      'timePosted': '18 weeks ago',
    },
    {
      'jobTitle': 'HR Specialist',
      'address': '2929 Pine Lane',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'HR Solutions',
      'location': 'Atlanta, Georgia, USA',
      'remoteStatus': 'Remote',
      'timePosted': '19 weeks ago',
    },
    {
      'jobTitle': 'Technical Support Engineer',
      'address': '3030 Oakridge Avenue',
      'image': 'https://via.placeholder.com/150',
      'companyName': 'Tech Support Experts',
      'location': 'Dallas, Texas, USA',
      'remoteStatus': 'Hybrid',
      'timePosted': '20 weeks ago',
    },
  ];
}
