List<Map<String, dynamic>> myNetwork = [
  {
    "name": "Anne Johnson",
    "designation": "Data Scientist",
    "timeAgo": "1 hour ago",
    "picture": "assets/images/person_avatars/person1.jpg",
    "location": "New York, NY, USA",
    "followers": 1500,
    "services": "Data Science , Machine Learning ,Analytics",
    "connections": 500,
    "college": "Anne University",
  },
  {
    "name": "Anna Anderson",
    "designation": "Product Manager",
    "timeAgo": "3 hours ago",
    "picture": "assets/images/person_avatars/person2.png",
    "location": "San Francisco, CA, USA",
    "followers": 5000,
    "services": "Product Management ,Product Launch , Marketing",
    "connections": 1000,
    "college": "Anna College",
  },
  {
    "name": "Annie White",
    "designation": "Graphic Designer",
    "timeAgo": "6 hours ago",
    "picture": "assets/images/person_avatars/person3.png",
    "location": "Los Angeles, CA, USA",
    "followers": 2000,
    "services": "Graphic Design ,Brand Identity , Illustration",
    "connections": 700,
    "college": "Annie Institute",
  },
  {
    "name": "Ann Brown",
    "designation": "Marketing Specialist",
    "timeAgo": "10 hours ago",
    "picture": "assets/images/person_avatars/person4.png",
    "location": "Chicago, IL, USA",
    "followers": 3000,
    "services": "Digital Marketing ,Content Strategy, Campaign Management",
    "connections": 900,
    "college": "Ann University",
  },
  {
    "name": "Ann Lee",
    "designation": "iOS Developer",
    "timeAgo": "12 hours ago",
    "picture": "assets/images/person_avatars/person5.jpg",
    "location": "Austin, TX, USA",
    "followers": 10000,
    "services": "iOS Development ,Mobile App Design ,User Experience",
    "connections": 1500,
    "college": "Ann College",
  },
];
