import 'package:linkedin_clone/utils/images/image_constants.dart';

List<Map<String, dynamic>> posts = [
  {
    "name": "Alice Johnson",
    "designation": "Data Scientist",
    "timeAgo": "1 hour ago",
    "picture": "assets/images/person_avatars/person1.jpg",
    "image": PostImages.postimage1,
    "likes": 1020,
    "description":
        "Just finished an exciting data science project. Happy to share my learnings!",
    "isliked": false,
    "comments": [],
    "location": "New York, NY, USA",
    "followers": 1500,
    "services": "Data Science , Machine Learning ,Analytics",
    "connections": 500,
    "college": "XYZ University",
  },
  {
    "name": "Bob Anderson",
    "designation": "Product Manager",
    "timeAgo": "3 hours ago",
    "picture": "assets/images/person_avatars/person2.png",
    "image": PostImages.postImage2,
    "likes": 32440,
    "description": "Launching a new product next week. Stay tuned for updates!",
    "isliked": false,
    "comments": [],
    "location": "San Francisco, CA, USA",
    "followers": 5000,
    "services": "Product Management ,Product Launch , Marketing",
    "connections": 1000,
    "college": "ABC College",
  },
  {
    "name": "Eva White",
    "designation": "Graphic Designer",
    "timeAgo": "6 hours ago",
    "picture": "assets/images/person_avatars/person3.png",
    "image": PostImages.postImage3,
    "likes": 3453,
    "description": "Designed a stunning new logo. Let me know your thoughts!",
    "isliked": false,
    "comments": [],
    "location": "Los Angeles, CA, USA",
    "followers": 2000,
    "services": "Graphic Design ,Brand Identity , Illustration",
    "connections": 700,
    "college": "PQR Institute",
  },
  {
    "name": "Charlie Brown",
    "designation": "Marketing Specialist",
    "timeAgo": "10 hours ago",
    "picture": "assets/images/person_avatars/person4.png",
    "image": PostImages.postImage4,
    "likes": 3453,
    "description":
        "Running a marketing campaign for our latest product. Exciting times ahead!",
    "isliked": false,
    "comments": [],
    "location": "Chicago, IL, USA",
    "followers": 3000,
    "services": "Digital Marketing ,Content Strategy, Campaign Management",
    "connections": 900,
    "college": "LMN University",
  },
  {
    "name": "Grace Lee",
    "designation": "iOS Developer",
    "timeAgo": "12 hours ago",
    "picture": "assets/images/person_avatars/person5.jpg",
    "image": PostImages.postImage5,
    "likes": 97970,
    "description":
        "Just released a major update for our mobile app. Check it out!",
    "isliked": false,
    "comments": [],
    "location": "Austin, TX, USA",
    "followers": 10000,
    "services": "iOS Development ,Mobile App Design ,User Experience",
    "connections": 1500,
    "college": "RST College",
  },
];
